{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vllm-deepseek.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vllm-deepseek.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vllm-deepseek.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vllm-deepseek.fullname" . }}
{{- end }}