{{- if .Values.model.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-deepseek.fullname" . }}-hf-token
  labels:
    app: {{ include "vllm-deepseek.name" . }}
type: Opaque
stringData:
  token: "{{ .Values.model.hfToken }}"
{{- end }}